# Generated by Django 3.0.3 on 2020-11-19 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='medals',
            field=models.ManyToManyField(blank=True, related_name='persons', through='api.PersonMedal', to='api.Medal'),
        ),
        migrations.AlterField(
            model_name='personmedal',
            name='medal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medals', to='api.Medal'),
        ),
        migrations.AlterField(
            model_name='personmedal',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='api.Person'),
        ),
    ]
