# Generated by Django 3.0.3 on 2020-11-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201119_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmedal',
            name='external_url',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='personmedal',
            name='extra',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='medals',
            field=models.ManyToManyField(blank=True, through='api.PersonMedal', to='api.Medal'),
        ),
    ]
