# Generated by Django 3.0.3 on 2020-11-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201119_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmedal',
            name='name',
            field=models.TextField(max_length=128, null=True),
        ),
    ]
