# Generated by Django 3.0.3 on 2020-11-20 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201119_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sport',
            old_name='name',
            new_name='sport',
        ),
        migrations.RemoveField(
            model_name='medal',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='event',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.TextField(max_length=256)),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sport')),
            ],
        ),
        migrations.AddField(
            model_name='medal',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Event'),
        ),
    ]
