# Generated by Django 3.0.3 on 2020-11-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201120_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personmedal',
            name='medal_id',
        ),
        migrations.RemoveField(
            model_name='personmedal',
            name='person_id',
        ),
        migrations.AddField(
            model_name='personmedal',
            name='medal2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Medal'),
        ),
        migrations.AddField(
            model_name='personmedal',
            name='person2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Person'),
        ),
    ]
