# Generated by Django 3.0.3 on 2020-11-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201120_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personmedal',
            old_name='medal2',
            new_name='medal',
        ),
        migrations.RenameField(
            model_name='personmedal',
            old_name='person2',
            new_name='person',
        ),
    ]
