# Generated by Django 3.0.3 on 2020-11-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201121_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='sport',
            new_name='name',
        ),
    ]
